erDiagram
    direction LR
    AccountAddonBillings ||--o{ Accounts } : "FK"
    AccountBillingItem ||--o{ Accounts } : "FK"
    AccountEventLog ||--o{ Accounts } : "FK"
    AccountPaymentGatewayBatchItem ||--o{ AccountPaymentGatewayBatch } : "FK"
    AccountPaymentGatewayBatchItem ||--o{ Accounts } : "FK"
    AccountProduct ||--o{ AccountProductCategory } : "FK"
    AccountProduct ||--o{ AccountProductSubCategory } : "FK"
    AccountProduct ||--o{ Accounts } : "FK"
    AccountProduct ||--o{ AccountSupplier } : "FK"
    AccountProduct ||--o{ DiscountCoupons } : "FK"
    AccountProductCategory ||--o{ Accounts } : "FK"
    AccountProductSubCategory ||--o{ AccountProductCategory } : "FK"
    AccountProductSubCategory ||--o{ Accounts } : "FK"
    AccountProductSupplier ||--o{ AccountProduct } : "FK"
    AccountProductSupplier ||--o{ Accounts } : "FK"
    AccountProductSupplier ||--o{ AccountSupplier } : "FK"
    AccountRoster ||--o{ Accounts } : "FK"
    AccountRoster ||--o{ Staff } : "FK"
    AccountRosterActivity ||--o{ Accounts } : "FK"
    AccountSupplier ||--o{ Accounts } : "FK"
    AccountSupplierOrderItems ||--o{ AccountProduct } : "FK"
    AccountSupplierOrderItems ||--o{ AccountSupplierOrders } : "FK"
    AccountSupplierOrders ||--o{ AccountSupplier } : "FK"
    AccountSupplierOrders ||--o{ Staff } : "FK"
    AmendedPayment ||--o{ Members } : "FK"
    AmendedPayment ||--o{ Staff } : "FK"
    AnalyticDashboardWidget ||--o{ AnalyticDashboard } : "FK"
    AnalyticDashboardWidget ||--o{ AnalyticWidgetConfiguration } : "FK"
    AppBrandingScreenConfiguration ||--o{ AppBrandingScreen } : "FK"
    aspnet_Membership ||--o{ aspnet_Applications } : "FK"
    aspnet_Membership ||--o{ aspnet_Users } : "FK"
    aspnet_Paths ||--o{ aspnet_Applications } : "FK"
    aspnet_PersonalizationAllUsers ||--o{ aspnet_Paths } : "FK"
    aspnet_PersonalizationPerUser ||--o{ aspnet_Paths } : "FK"
    aspnet_PersonalizationPerUser ||--o{ aspnet_Users } : "FK"
    aspnet_Profile ||--o{ aspnet_Users } : "FK"
    aspnet_Roles ||--o{ aspnet_Applications } : "FK"
    aspnet_Users ||--o{ aspnet_Applications } : "FK"
    aspnet_UsersInRoles ||--o{ aspnet_Roles } : "FK"
    aspnet_UsersInRoles ||--o{ aspnet_Users } : "FK"
    AttendanceLog ||--o{ Accounts } : "FK"
    AttendanceLog ||--o{ Members } : "FK"
    BirthdayEmailAttachments ||--o{ MarketingBirthdayCampaign } : "FK"
    BookingType ||--o{ Accounts } : "FK"
    Campaign ||--o{ Accounts } : "FK"
    Campaign ||--o{ CampaignType } : "FK"
    Campaign ||--o{ Group } : "FK"
    Campaign ||--o{ MarketingEmailTemplate } : "FK"
    Campaign ||--o{ aspnet_Users } : "FK"
    CampaignFilterOptions ||--o{ CampaignFilters } : "FK"
    CampaignMessageSent ||--o{ Campaign } : "FK"
    CampaignTemplate ||--o{ MarketingEmailTemplate } : "FK"
    Class ||--o{ Accounts } : "FK"
    Class ||--o{ aspnet_Users } : "FK"
    ClassSchedule ||--o{ Accounts } : "FK"
    ClassSchedule ||--o{ Class } : "FK"
    ClassSchedule ||--o{ Trainer } : "FK"
    ClassScheduleAgeRestriction ||--o{ ClassSchedule } : "FK"
    ClassScheduleAttendanceCount ||--o{ ClassSchedule } : "FK"
    ClassScheduleChangedInstructor ||--o{ Trainer } : "FK"
    ClassScheduleChangedInstructor ||--o{ ClassSchedule } : "FK"
    ClassScheduleChanges ||--o{ ClassSchedule } : "FK"
    ClassScheduleMobileAccount ||--o{ ClassSchedule } : "FK"
    ClassScheduleMobileAccount ||--o{ Lookup_Type_Items } : "FK"
    ClassScheduleMobileAccount ||--o{ Staff } : "FK"
    ClassScheduleOnDemand ||--o{ ClassSchedule } : "FK"
    ClassScheduleOnlineAccount ||--o{ ClassSchedule } : "FK"
    ClassScheduleOnlineAccount ||--o{ OnlineAccount } : "FK"
    Club_Number_Audit ||--o{ Accounts } : "FK"
    ClubActivityEod ||--o{ Accounts } : "FK"
    ClubActivityEod ||--o{ Staff } : "FK"
    Court ||--o{ Accounts } : "FK"
    CourtAvailability ||--o{ Court } : "FK"
    CourtBookings ||--o{ BookingType } : "FK"
    CourtBookings ||--o{ Court } : "FK"
    DigitalDoorTimezone ||--o{ Accounts } : "FK"
    DigitalSignature ||--o{ Members } : "FK"
    DiscountCoupons ||--o{ Staff } : "FK"
    EmailTemplateAttachments ||--o{ MarketingEmailTemplate } : "FK"
    EntityTags ||--o{ Accounts } : "FK"
    Exercise ||--o{ ExerciseBodyPart } : "FK"
    ExerciseDataTypeUnit ||--o{ ExerciseDataType } : "FK"
    FacebookLeads ||--o{ Accounts } : "FK"
    FitnessTestingType ||--o{ Lookup_Type_Items } : "FK"
    FormFieldMapping ||--o{ Fields } : "FK"
    FormFieldMapping ||--o{ Forms } : "FK"
    Forms ||--o{ FormTypes } : "FK"
    Gateway_Audit ||--o{ Members } : "FK"
    GroupClassScheduleExcludedTime ||--o{ ClassSchedule } : "FK"
    GroupClassScheduleExcludedTime ||--o{ Staff } : "FK"
    GroupType ||--o{ Accounts } : "FK"
    GroupTypeLinkToMembershipType ||--o{ GroupType } : "FK"
    GroupTypeLinkToMembershipType ||--o{ MembershipTypes } : "FK"
    GuestTrainerBookingAttendance ||--o{ TrainerBookingGuest } : "FK"
    Holidays ||--o{ Accounts } : "FK"
    Icons ||--o{ Accounts } : "FK"
    Icons ||--o{ Staff } : "FK"
    Invoice ||--o{ Accounts } : "FK"
    Invoice ||--o{ Contacts } : "FK"
    Invoice ||--o{ Members } : "FK"
    Invoice ||--o{ Staff } : "FK"
    InvoiceItem ||--o{ Invoice } : "FK"
    Kpi ||--o{ Accounts } : "FK"
    Lookup_Type_Items ||--o{ Lookup_Types } : "FK"
    MarketingEmailTemplate ||--o{ aspnet_Users } : "FK"
    MasterCalendarBlock ||--o{ MasterCalendarBlockParent } : "FK"
    MemberAccessSync ||--o{ Accounts } : "FK"
    MemberAccessSync ||--o{ Members } : "FK"
    MemberActivity ||--o{ Members } : "FK"
    MemberActivity ||--o{ Staff } : "FK"
    MemberAgreementHistory ||--o{ Members } : "FK"
    MemberAppointment ||--o{ Members } : "FK"
    MemberAppointment ||--o{ Staff } : "FK"
    MemberArchiveReason ||--o{ Lookup_Type_Items } : "FK"
    MemberArchiveReason ||--o{ Members } : "FK"
    MemberArrears ||--o{ Members } : "FK"
    MemberAttachment ||--o{ Members } : "FK"
    MemberAttendanceRestrictionMultiple ||--o{ MemberAttendanceRestriction } : "FK"
    MemberBillingItem ||--o{ MemberKid } : "FK"
    MemberBillingItem ||--o{ Members } : "FK"
    MemberCall ||--o{ Members } : "FK"
    MemberCall ||--o{ Staff } : "FK"
    MemberChangeAudit ||--o{ Members } : "FK"
    MemberCommunicationFailedLogs ||--o{ Members } : "FK"
    MemberCreditCard ||--o{ Members } : "FK"
    MemberDebtCollection ||--o{ Members } : "FK"
    MemberDisputes ||--o{ Members } : "FK"
    MemberFailedPayment ||--o{ Members } : "FK"
    MemberFamilyLink ||--o{ Members } : "FK"
    MemberFingerprint ||--o{ Members } : "FK"
    MemberFitnessTesting ||--o{ FitnessTestingType } : "FK"
    MemberFitnessTesting ||--o{ Members } : "FK"
    MemberGroup ||--o{ GroupType } : "FK"
    MemberGroup ||--o{ Members } : "FK"
    MemberGroup ||--o{ Staff } : "FK"
    MemberGroupClassAttendanceLog ||--o{ Accounts } : "FK"
    MemberGroupClassAttendanceLog ||--o{ ClassSchedule } : "FK"
    MemberGroupClassSubscription ||--o{ Members } : "FK"
    MemberKid ||--o{ Members } : "FK"
    MemberMeasurements ||--o{ Members } : "FK"
    MemberMeasurements ||--o{ Staff } : "FK"
    MemberMedicalConditions ||--o{ Members } : "FK"
    MemberMembershipTypeChangeHistory ||--o{ Members } : "FK"
    MemberMembershipTypeChangeHistory ||--o{ Staff } : "FK"
    MemberNotes ||--o{ Accounts } : "FK"
    MemberNotes ||--o{ Members } : "FK"
    MemberOrientationQuestionnaire ||--o{ OrientationQuestionnaire } : "FK"
    MemberOrientationQuestionnaire ||--o{ OrientationQuestionnaireGroup } : "FK"
    MemberOrientationQuestionnaire ||--o{ Members } : "FK"
    MemberOtherFeeRunLog ||--o{ Accounts } : "FK"
    MemberOtherFeeRunLog ||--o{ Staff } : "FK"
    MemberOtherMembership ||--o{ Members } : "FK"
    MemberOtherMembership ||--o{ MembershipTypes } : "FK"
    MemberOtherMembership ||--o{ PaymentHistory } : "FK"
    MemberParentGuarantor ||--o{ Members } : "FK"
    MemberPaymentGatewayTransactionAudit ||--o{ Members } : "FK"
    MemberPaymentGatewayTransactionAudit ||--o{ MembershipTypes } : "FK"
    MemberPaymentGatewayTransactionAudit ||--o{ PaymentGateway } : "FK"
    MemberPaymentTemplates ||--o{ DiscountCoupons } : "FK"
    MemberPaymentTemplates ||--o{ Members } : "FK"
    MemberPaymentTemplates ||--o{ MembershipTypes } : "FK"
    MemberPaymentTemplates ||--o{ PaymentGateway } : "FK"
    MemberPaymentVariation ||--o{ Members } : "FK"
    MemberPreActivityQuestionnaire ||--o{ PreActivityQuestionaire } : "FK"
    MemberPreActivityQuestionnaire ||--o{ PreActivityQuestionaireGroup } : "FK"
    MemberPreActivityQuestionnaire ||--o{ Members } : "FK"
    MemberPtSubscription ||--o{ Members } : "FK"
    MemberReferrals ||--o{ Prospects } : "FK"
    MemberRestrictedGroupClass ||--o{ Members } : "FK"
    MemberRestrictedGroupClass ||--o{ Class } : "FK"
    MemberRewardsProgram ||--o{ Members } : "FK"
    MemberRewardsProgram ||--o{ RewardsProgram } : "FK"
    MemberRewardsProgram ||--o{ RewardsProgramPointLevel } : "FK"
    MemberRewardsProgramLevelHistory ||--o{ Members } : "FK"
    MemberRewardsProgramLevelHistory ||--o{ RewardsProgram } : "FK"
    MemberRewardsProgramLevelHistory ||--o{ RewardsProgramPointLevel } : "FK"
    Members ||--o{ Accounts } : "FK"
    Members ||--o{ Prospects } : "FK"
    Members ||--o{ Staff } : "FK"
    MemberSession ||--o{ Staff } : "FK"
    MembershipTypeAccount ||--o{ Accounts } : "FK"
    MembershipTypeAccount ||--o{ MembershipTypes } : "FK"
    MembershipTypes ||--o{ MemberAttendanceRestriction } : "FK"
    MembershipTypes ||--o{ MembershipContractTypes } : "FK"
    MembershipTypes ||--o{ Staff } : "FK"
    MemberSubscription ||--o{ Members } : "FK"
    MemberSubscription ||--o{ PosTransaction } : "FK"
    MemberSubscription ||--o{ Subscription } : "FK"
    MemberSubscriptionAudit ||--o{ Members } : "FK"
    MemberSubscriptionAudit ||--o{ MemberSubscription } : "FK"
    MemberSubscriptionAudit ||--o{ Staff } : "FK"
    MemberSubscriptionAudit ||--o{ Trainer } : "FK"
    MemberSuspension ||--o{ Members } : "FK"
    MemberTracking ||--o{ Accounts } : "FK"
    MemberTracking ||--o{ MarketingEmailTemplate } : "FK"
    MemberTrackingSchedule ||--o{ Members } : "FK"
    MemberTrackingSchedule ||--o{ MemberTracking } : "FK"
    MemberTrackingSchedule ||--o{ Staff } : "FK"
    MemberTrainerBookingAttendance ||--o{ Members } : "FK"
    MemberTrainerBookingAttendance ||--o{ Trainer } : "FK"
    MemberTrainerBookingAttendance ||--o{ TrainerBookingGuest } : "FK"
    MemberVerificationCode ||--o{ Members } : "FK"
    MemberViewNotes ||--o{ Lookup_Type_Items } : "FK"
    MemberViewNotes ||--o{ Members } : "FK"
    MemberViewNotes ||--o{ Accounts } : "FK"
    MemberVisit ||--o{ Staff } : "FK"
    MemberVouchers ||--o{ Members } : "FK"
    MemberVouchers ||--o{ aspnet_Users } : "FK"
    MemberVouchers ||--o{ Vouchers } : "FK"
    MyClubMemberProfile ||--o{ Members } : "FK"
    NewsFeed ||--o{ Accounts } : "FK"
    NewsFeed ||--o{ aspnet_Users } : "FK"
    OnlineShopTransaction ||--o{ Accounts } : "FK"
    OnlineShopTransaction ||--o{ Staff } : "FK"
    OnlineShopTransactionItem ||--o{ AccountProduct } : "FK"
    OnlineShopTransactionItem ||--o{ OnlineShopTransaction } : "FK"
    OnlineShopTransactionPayment ||--o{ OnlineShopTransaction } : "FK"
    OptoutHistory ||--o{ Members } : "FK"
    OptoutHistory ||--o{ Prospects } : "FK"
    OptoutHistory ||--o{ Staff } : "FK"
    OptoutHistory ||--o{ Students } : "FK"
    OrientationQuestionnaire ||--o{ OrientationQuestionnaireGroup } : "FK"
    OrientationQuestionnaireGroup ||--o{ Accounts } : "FK"
    OrientationQuestionnaireParent ||--o{ Accounts } : "FK"
    Page ||--o{ PageGroup } : "FK"
    PageAction ||--o{ Page } : "FK"
    PaymentDateChangeHistory ||--o{ Members } : "FK"
    PaymentDateChangeHistory ||--o{ Staff } : "FK"
    PaymentGatewayBatchItem ||--o{ Members } : "FK"
    PaymentGatewayBatchItem ||--o{ PaymentGatewayBatch } : "FK"
    PaymentHistory ||--o{ Members } : "FK"
    PosTillSummary ||--o{ PosTillSummaryNote } : "FK"
    PosTransaction ||--o{ Accounts } : "FK"
    PosTransaction ||--o{ Staff } : "FK"
    PosTransaction ||--o{ Members } : "FK"
    PosTransactionAudit ||--o{ Members } : "FK"
    PosTransactionAudit ||--o{ PosTransaction } : "FK"
    PosTransactionAudit ||--o{ Staff } : "FK"
    PosTransactionGenericItem ||--o{ MembershipTypes } : "FK"
    PosTransactionGenericItem ||--o{ PosTransaction } : "FK"
    PosTransactionItem ||--o{ AccountProduct } : "FK"
    PosTransactionItem ||--o{ PosTransaction } : "FK"
    PosTransactionPayment ||--o{ PosTransaction } : "FK"
    PreActivityQuestionaire ||--o{ PreActivityQuestionaireGroup } : "FK"
    PreActivityQuestionaireGroup ||--o{ Accounts } : "FK"
    PreActivityQuestionaireParent ||--o{ Accounts } : "FK"
    ProspectActivity ||--o{ Prospects } : "FK"
    ProspectActivity ||--o{ Staff } : "FK"
    ProspectAppointment ||--o{ Staff } : "FK"
    ProspectAppointment ||--o{ Prospects } : "FK"
    ProspectAttachment ||--o{ Prospects } : "FK"
    ProspectAttendanceLog ||--o{ Accounts } : "FK"
    ProspectCall ||--o{ Staff } : "FK"
    ProspectCall ||--o{ Prospects } : "FK"
    ProspectCall ||--o{ ProspectTracking } : "FK"
    ProspectCommunicationFailedLogs ||--o{ Prospects } : "FK"
    ProspectCreditCard ||--o{ Prospects } : "FK"
    ProspectKid ||--o{ Prospects } : "FK"
    ProspectMasterCalendarBlock ||--o{ ProspectMasterCalendarBlockParent } : "FK"
    ProspectMedicalConditions ||--o{ Prospects } : "FK"
    ProspectMembersCancelled ||--o{ Accounts } : "FK"
    ProspectMembersCancelled ||--o{ Staff } : "FK"
    ProspectNotes ||--o{ Prospects } : "FK"
    ProspectParentGuarantor ||--o{ Prospects } : "FK"
    ProspectPaymentGatewayTransactionAudit ||--o{ PaymentGateway } : "FK"
    ProspectPaymentGatewayTransactionAudit ||--o{ Prospects } : "FK"
    ProspectPaymentHistory ||--o{ Prospects } : "FK"
    ProspectPosTransaction ||--o{ Accounts } : "FK"
    ProspectPosTransaction ||--o{ Staff } : "FK"
    ProspectPosTransaction ||--o{ Prospects } : "FK"
    ProspectPosTransactionAudit ||--o{ ProspectPosTransaction } : "FK"
    ProspectPosTransactionAudit ||--o{ Prospects } : "FK"
    ProspectPosTransactionAudit ||--o{ Staff } : "FK"
    ProspectPosTransactionItem ||--o{ AccountProduct } : "FK"
    ProspectPosTransactionItem ||--o{ ProspectPosTransaction } : "FK"
    ProspectPosTransactionPayment ||--o{ ProspectPosTransaction } : "FK"
    ProspectPreActivityQuestionnaire ||--o{ PreActivityQuestionaire } : "FK"
    ProspectPreActivityQuestionnaire ||--o{ PreActivityQuestionaireGroup } : "FK"
    ProspectPreActivityQuestionnaire ||--o{ Prospects } : "FK"
    Prospects ||--o{ Accounts } : "FK"
    Prospects ||--o{ Staff } : "FK"
    ProspectToDo ||--o{ Prospects } : "FK"
    ProspectToDo ||--o{ Staff } : "FK"
    ProspectTracking ||--o{ MarketingEmailTemplate } : "FK"
    ProspectTrackingSchedule ||--o{ Prospects } : "FK"
    ProspectTrackingSchedule ||--o{ ProspectTracking } : "FK"
    ProspectTrackingSchedule ||--o{ Staff } : "FK"
    ProspectTrainerBookingAttendance ||--o{ Prospects } : "FK"
    ProspectTrainerBookingAttendance ||--o{ Trainer } : "FK"
    ProspectVerificationCode ||--o{ Prospects } : "FK"
    RestrictedDiscountCoupons ||--o{ DiscountCoupons } : "FK"
    RestrictedDiscountCoupons ||--o{ MembershipTypes } : "FK"
    RestrictedGroupClass ||--o{ Class } : "FK"
    RestrictedGroupClass ||--o{ MembershipTypes } : "FK"
    RewardsProgram ||--o{ aspnet_Users } : "FK"
    RewardsProgramAccount ||--o{ Accounts } : "FK"
    RewardsProgramAccount ||--o{ RewardsProgram } : "FK"
    RewardsProgramClassPointsAllocation ||--o{ Class } : "FK"
    RewardsProgramClassPointsAllocation ||--o{ RewardsProgram } : "FK"
    RewardsProgramPointLevel ||--o{ RewardsProgram } : "FK"
    RewardsProgramPointsAudit ||--o{ Class } : "FK"
    RewardsProgramPointsAudit ||--o{ Members } : "FK"
    RewardsProgramPointsAudit ||--o{ RewardsProgram } : "FK"
    RolePage ||--o{ aspnet_Roles } : "FK"
    RolePage ||--o{ Page } : "FK"
    RolePageAction ||--o{ aspnet_Roles } : "FK"
    RolePageAction ||--o{ PageAction } : "FK"
    RoomAvailability ||--o{ Rooms } : "FK"
    RoomBookings ||--o{ BookingType } : "FK"
    RoomBookings ||--o{ Rooms } : "FK"
    Settlement ||--o{ Accounts } : "FK"
    SocialTagMapping ||--o{ Accounts } : "FK"
    Staff ||--o{ Accounts } : "FK"
    StaffAccount ||--o{ Accounts } : "FK"
    StaffAccount ||--o{ Staff } : "FK"
    StaffAttachments ||--o{ Staff } : "FK"
    StaffAttendanceLog ||--o{ Accounts } : "FK"
    StaffAttendanceLog ||--o{ Staff } : "FK"
    StaffCertifications ||--o{ Staff } : "FK"
    StaffFingerprint ||--o{ Staff } : "FK"
    StaffNotes ||--o{ Accounts } : "FK"
    StaffNotes ||--o{ Staff } : "FK"
    StaffReports ||--o{ Accounts } : "FK"
    StaffReports ||--o{ Staff } : "FK"
    StaffSettings ||--o{ Staff } : "FK"
    StaffShift ||--o{ Staff } : "FK"
    StaffTask ||--o{ aspnet_Users } : "FK"
    StaffTask ||--o{ Members } : "FK"
    StaffTaskAssignee ||--o{ Staff } : "FK"
    StaffTaskAssignee ||--o{ StaffTask } : "FK"
    StaffTaskAttachment ||--o{ aspnet_Users } : "FK"
    StaffTimesheet ||--o{ Staff } : "FK"
    StaffTrainerAccess ||--o{ Staff } : "FK"
    StaffTrainerAccess ||--o{ Trainer } : "FK"
    Stocktakes ||--o{ AccountProduct } : "FK"
    Stocktakes ||--o{ Accounts } : "FK"
    Stocktakes ||--o{ Staff } : "FK"
    StudentArrears ||--o{ Students } : "FK"
    StudentAttachment ||--o{ Students } : "FK"
    StudentAttendanceLog ||--o{ Accounts } : "FK"
    StudentAttendanceLog ||--o{ Students } : "FK"
    StudentAttendanceLog ||--o{ SwimClassSchedule } : "FK"
    StudentBillingItem ||--o{ Students } : "FK"
    StudentCancelledClasses ||--o{ StudentSwimClassBookingDetail } : "FK"
    StudentCancelledFromWholeClasses ||--o{ Students } : "FK"
    StudentCancelledFromWholeClasses ||--o{ SwimClassSchedule } : "FK"
    StudentChangedClassHistory ||--o{ Staff } : "FK"
    StudentChangedClassHistory ||--o{ Students } : "FK"
    StudentChangedClassHistory ||--o{ SwimClassSchedule } : "FK"
    StudentClassCreditHistory ||--o{ Staff } : "FK"
    StudentClassCreditHistory ||--o{ StudentPosTransaction } : "FK"
    StudentClassCreditHistory ||--o{ Students } : "FK"
    StudentClassCreditHistory ||--o{ SwimClassSchedule } : "FK"
    StudentClassWaitList ||--o{ Students } : "FK"
    StudentClassWaitList ||--o{ SwimClassSchedule } : "FK"
    StudentCommunicationFailedLogs ||--o{ Students } : "FK"
    StudentDigitalSignature ||--o{ Students } : "FK"
    StudentFamily ||--o{ Accounts } : "FK"
    StudentFamily ||--o{ Staff } : "FK"
    StudentFamilyLink ||--o{ StudentFamily } : "FK"
    StudentFamilyLink ||--o{ Students } : "FK"
    StudentFullClassSchedule ||--o{ StudentSwimClassBookingDetail } : "FK"
    StudentNotes ||--o{ Staff } : "FK"
    StudentNotes ||--o{ Students } : "FK"
    StudentPaymentGatewayBatchItem ||--o{ StudentPaymentGatewayBatch } : "FK"
    StudentPaymentGatewayBatchItem ||--o{ Students } : "FK"
    StudentPaymentGatewayTransactionAudit ||--o{ PaymentGateway } : "FK"
    StudentPaymentGatewayTransactionAudit ||--o{ Students } : "FK"
    StudentPaymentHistory ||--o{ Students } : "FK"
    StudentPaymentTemplates ||--o{ PaymentGateway } : "FK"
    StudentPaymentTemplates ||--o{ Students } : "FK"
    StudentPaymentTemplates ||--o{ StudentSwimClassBookingDetail } : "FK"
    StudentPaymentVariation ||--o{ StudentPaymentTemplates } : "FK"
    StudentPIFHistory ||--o{ StudentPosTransaction } : "FK"
    StudentPosTransaction ||--o{ Staff } : "FK"
    StudentPosTransaction ||--o{ Students } : "FK"
    StudentPosTransactionGenericItem ||--o{ MembershipTypes } : "FK"
    StudentPosTransactionGenericItem ||--o{ StudentPosTransaction } : "FK"
    StudentPosTransactionItem ||--o{ StudentPosTransaction } : "FK"
    StudentPosTransactionPayment ||--o{ StudentPosTransaction } : "FK"
    StudentRemoveFromSwimClassBooking ||--o{ StudentSwimClassBookingDetail } : "FK"
    StudentRemoveFromSwimClassBooking ||--o{ SwimClassSchedule } : "FK"
    Students ||--o{ Accounts } : "FK"
    StudentSwimClassBookingDetail ||--o{ Prospects } : "FK"
    StudentSwimClassBookingDetail ||--o{ StudentPosTransaction } : "FK"
    StudentSwimClassBookingDetail ||--o{ Students } : "FK"
    StudentSwimClassBookingDetail ||--o{ SwimClassSchedule } : "FK"
    StudentSwimSkills ||--o{ Lookup_Type_Items } : "FK"
    StudentSwimSkills ||--o{ Students } : "FK"
    StudentTasks ||--o{ Accounts } : "FK"
    StudentTasks ||--o{ Students } : "FK"
    Subscription ||--o{ DiscountCoupons } : "FK"
    Subscription ||--o{ Lookup_Type_Items } : "FK"
    SwimClass ||--o{ Accounts } : "FK"
    SwimClass ||--o{ aspnet_Users } : "FK"
    SwimClassSchedule ||--o{ Accounts } : "FK"
    SwimClassSchedule ||--o{ SwimClass } : "FK"
    SwimClassSchedule ||--o{ Trainer } : "FK"
    SwimClassScheduleChangedInstructor ||--o{ Trainer } : "FK"
    SwimClassScheduleChangedInstructor ||--o{ SwimClassSchedule } : "FK"
    SwimClassScheduleOnlineAccount ||--o{ OnlineAccount } : "FK"
    SwimClassScheduleOnlineAccount ||--o{ SwimClassSchedule } : "FK"
    SwimClassScheduleTerm ||--o{ SwimClassSchedule } : "FK"
    SwimClassScheduleTerm ||--o{ SwimTerm } : "FK"
    SwimScheduleExcludedTime ||--o{ Staff } : "FK"
    SwimScheduleExcludedTime ||--o{ SwimClassSchedule } : "FK"
    SwimStocktakes ||--o{ AccountProduct } : "FK"
    SwimStocktakes ||--o{ Accounts } : "FK"
    SwimStocktakes ||--o{ Staff } : "FK"
    TrainerAccount ||--o{ Accounts } : "FK"
    TrainerAccount ||--o{ Trainer } : "FK"
    TrainerAttachments ||--o{ Trainer } : "FK"
    TrainerAttendanceLog ||--o{ Accounts } : "FK"
    TrainerAttendanceLog ||--o{ Trainer } : "FK"
    TrainerBooking ||--o{ aspnet_Users } : "FK"
    TrainerBooking ||--o{ Members } : "FK"
    TrainerBooking ||--o{ Prospects } : "FK"
    TrainerBooking ||--o{ Staff } : "FK"
    TrainerBooking ||--o{ Trainer } : "FK"
    TrainerBooking ||--o{ TrainerBookingGuest } : "FK"
    TrainerBookingTypePricing ||--o{ BookingType } : "FK"
    TrainerBookingTypePricing ||--o{ Trainer } : "FK"
    TrainerCertifications ||--o{ Trainer } : "FK"
    TrainerNotes ||--o{ Accounts } : "FK"
    TrainerNotes ||--o{ Trainer } : "FK"
    TrainerShift ||--o{ Trainer } : "FK"
    TrainerShiftBlock ||--o{ Trainer } : "FK"
    TrainerShiftBlock ||--o{ TrainerShiftBlockParent } : "FK"
    TrainerShiftBlockParent ||--o{ Trainer } : "FK"
    UserLogActivity ||--o{ aspnet_Users } : "FK"
    VendorMemberSetting ||--o{ Members } : "FK"
    Vouchers ||--o{ Accounts } : "FK"
    Vouchers ||--o{ aspnet_Users } : "FK"
    Workout ||--o{ Staff } : "FK"
    Workout ||--o{ Members } : "FK"
    Workout ||--o{ WorkoutTemplate } : "FK"
    WorkoutGroup ||--o{ Workout } : "FK"
    WorkoutGroupExercise ||--o{ Exercise } : "FK"
    WorkoutGroupExercise ||--o{ WorkoutGroup } : "FK"
    WorkoutGroupExerciseComment ||--o{ WorkoutGroupExercise } : "FK"
    WorkoutGroupExerciseSet ||--o{ ExerciseDataType } : "FK"
    WorkoutGroupExerciseSet ||--o{ ExerciseDataTypeUnit } : "FK"
    WorkoutGroupExerciseSet ||--o{ WorkoutGroupExercise } : "FK"
    WorkoutGroupExerciseSetResult ||--o{ WorkoutGroupExerciseSet } : "FK"
    WorkoutMemberGroup ||--o{ GroupType } : "FK"
    WorkoutTemplate ||--o{ Staff } : "FK"
    WorkoutTemplate ||--o{ Lookup_Type_Items } : "FK"
    WorkoutTemplateGroup ||--o{ WorkoutTemplate } : "FK"
    WorkoutTemplateGroupExercise ||--o{ Exercise } : "FK"
    WorkoutTemplateGroupExercise ||--o{ WorkoutTemplateGroup } : "FK"
    WorkoutTemplateGroupExercise ||--o{ WorkoutTemplateGroupExercise } : "FK"
    WorkoutTemplateGroupExerciseSet ||--o{ ExerciseDataType } : "FK"
    WorkoutTemplateGroupExerciseSet ||--o{ ExerciseDataTypeUnit } : "FK"
    WorkoutTemplateGroupExerciseSet ||--o{ WorkoutTemplateGroupExercise } : "FK"