USE [hkietech]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[ExerciseDataType](
	[ExerciseDataTypeId] [int] IDENTITY(1,1) NOT NULL,
	[ExerciseDataTypeName] [varchar](80) NULL,
 CONSTRAINT [PK_ExerciseDataType] PRIMARY KEY CLUSTERED 
(
	[ExerciseDataTypeId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
