USE [hkietech]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[ExerciseBodyPart](
	[ExerciseBodyPartId] [int] IDENTITY(1,1) NOT NULL,
	[BodyPartName] [varchar](100) NULL,
 CONSTRAINT [PK_ExerciseBodyPart] PRIMARY KEY CLUSTERED 
(
	[ExerciseBodyPartId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
