USE [hkietech]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Forms](
	[FormId] [int] IDENTITY(1,1) NOT NULL,
	[FormName] [nvarchar](100) NOT NULL,
	[FormTypeId] [int] NULL,
	[S3FormLocation] [nvarchar](200) NULL,
 CONSTRAINT [PK_Forms] PRIMARY KEY CLUSTERED 
(
	[FormId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[Forms]  WITH CHECK ADD  CONSTRAINT [FK_Forms_FormTypes] FOREIGN KEY([FormTypeId])
REFERENCES [dbo].[FormTypes] ([FormTypeId])
GO
ALTER TABLE [dbo].[Forms] CHECK CONSTRAINT [FK_Forms_FormTypes]
GO
