USE [hkietech]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[FormTypes](
	[FormTypeId] [int] IDENTITY(1,1) NOT NULL,
	[FormTypeName] [nvarchar](100) NOT NULL,
 CONSTRAINT [PK_FormTypes] PRIMARY KEY CLUSTERED 
(
	[FormTypeId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
