USE [hkietech]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Kpi](
	[KpiId] [bigint] IDENTITY(1,1) NOT NULL,
	[KpiKey] [nvarchar](50) NOT NULL,
	[KpiValue] [decimal](19, 6) NOT NULL,
	[KpiDateTime] [datetime] NOT NULL,
	[account_id] [int] NOT NULL,
 CONSTRAINT [PK_Kpi] PRIMARY KEY CLUSTERED 
(
	[KpiId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[Kpi]  WITH CHECK ADD  CONSTRAINT [FK_Kpi_Accounts] FOREIGN KEY([account_id])
REFERENCES [dbo].[Accounts] ([account_id])
GO
ALTER TABLE [dbo].[Kpi] CHECK CONSTRAINT [FK_Kpi_Accounts]
GO
