USE [hkietech]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[MyClubUserDevice](
	[Id] [bigint] IDENTITY(1,1) NOT NULL,
	[Number] [varchar](20) NOT NULL,
	[DeviceId] [nvarchar](1000) NOT NULL,
	[Platform] [nvarchar](100) NULL,
 CONSTRAINT [PK_MyClubUserDevice] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
