USE [hkietech]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[PageTemplate](
	[PageTemplateId] [int] IDENTITY(1,1) NOT NULL,
	[CompanyCode] [varchar](50) NOT NULL,
	[DepartmentId] [int] NOT NULL,
	[TemplatePath] [varchar](100) NOT NULL,
 CONSTRAINT [PK_PageTemplate] PRIMARY KEY CLUSTERED 
(
	[PageTemplateId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
