USE [hkietech]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[WebhookAudit](
	[WebhookAuditId] [bigint] IDENTITY(1,1) NOT NULL,
	[Partner] [varchar](50) NOT NULL,
	[Event] [varchar](100) NOT NULL,
	[Data] [text] NOT NULL,
	[ReceivedUtcDateTime] [datetime] NOT NULL,
	[ProcessedUtcDateTime] [datetime] NULL,
 CONSTRAINT [PK_WebhookAudit] PRIMARY KEY CLUSTERED 
(
	[WebhookAuditId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
