USE [hkietech]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[WorkoutGroup](
	[WorkoutGroupId] [int] IDENTITY(1,1) NOT NULL,
	[WorkoutId] [int] NOT NULL,
	[GroupId] [int] NOT NULL,
 CONSTRAINT [PK_WorkoutGroup] PRIMARY KEY CLUSTERED 
(
	[WorkoutGroupId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[WorkoutGroup]  WITH CHECK ADD  CONSTRAINT [FK_WorkoutGroup_Workout] FOREIGN KEY([WorkoutId])
REFERENCES [dbo].[Workout] ([WorkoutId])
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[WorkoutGroup] CHECK CONSTRAINT [FK_WorkoutGroup_Workout]
GO
