USE [hkietech]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[WorkoutMemberGroup](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[MemberGroupId] [int] NOT NULL,
	[BatchId] [varchar](100) NOT NULL,
 CONSTRAINT [PK_WorkoutMemberGroup] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[WorkoutMemberGroup]  WITH CHECK ADD  CONSTRAINT [FK_WorkoutMemberGroup_GroupTypes] FOREIGN KEY([MemberGroupId])
REFERENCES [dbo].[GroupType] ([GroupId])
GO
ALTER TABLE [dbo].[WorkoutMemberGroup] CHECK CONSTRAINT [FK_WorkoutMemberGroup_GroupTypes]
GO
